Test branch
Fireinfern/tournament-frontend pull request #10
Opened 2023-04-04 00:06 UTC by respatica

2023-04-06 02:09 UTC, Fireinfern requested changes
If this is ready for merge, pls fix merge conflicts with master

2023-04-07 20:59 UTC, Fireinfern requested changes
Some things are working, couldn't test them all, but some things have to be changed

2023-04-07 20:59 UTC, Fireinfern commented on src/app/dialogs/login/login.component.ts
> +
Why f, try a better name, don't know what it refers to

2023-04-07 20:59 UTC, Fireinfern commented on src/app/dialogs/login/login.component.html
> +                      </div>
Use mat-error tag instead

2023-04-07 21:21 UTC, respatica commented on src/app/dialogs/login/login.component.html
> +                      </div>
it change from so many pulls

2023-04-08 03:04 UTC, Fireinfern approved these changes
LGTM

2023-04-08 03:04 UTC, merged