test in winner announcement in details page
Fireinfern/tournament-frontend pull request #13
Opened 2023-04-07 05:20 UTC by Theepanguna

I did a small test on the winner announcement on the details page.  is the logic okay or should I do it differently, I have pushed to the new branch feature/winner_announcement.

2023-04-07 17:09 UTC, Fireinfern requested changes
The logic is a little bit faulty, it doesnt make sense to simple change to the last tab and see the winner, also, you arent accounting for the tournaments of 3 rounds

2023-04-07 17:09 UTC, Fireinfern commented on src/app/views/tournament/tournament.component.ts
> +  }
This doesn't makes sense, you aren't waiting the person to show the winners tab, you are waiting that a player is marked as winner in the last round, then, you can change to the winner tab or use a dialog

2023-04-08 12:36 UTC, Fireinfern reviewed
This looks good, do you need anything else so it can be approved?

2023-04-08 12:54 UTC, Theepanguna commented
Yes, is it possible to have one test data from the Backend for rounds 2 and round 3. 
I tried to add a player but I guess still, we have not completed that task. 
(Because I think sometimes I need to check whether the round is completed or not.)

if there is any improvement needed on this I can work on it.
> This looks good, do you need anything else so it can be approved?

2023-04-10 00:31 UTC, Theepanguna commented
Tested winner dialog is pushed to the branch for final approval

2023-04-10 01:44 UTC, Fireinfern approved these changes
LGTM

2023-04-10 01:44 UTC, merged