Tournament creation in menu bar
Fireinfern/tournament-frontend pull request #4
Opened 2023-03-23 00:24 UTC by Theepanguna

2023-03-23 00:28 UTC, Theepanguna commented
I have created a tournament create and tournament display menu bar. This is v1, let me know the feedback so I will work furthermore

2023-03-24 00:02 UTC, Fireinfern requested changes
Overall good, some changes will be needed

2023-03-24 00:02 UTC, SebastianSilvaDev commented on src/app/app-routing.module.ts
> +  { path: 'tournamentCreate', component: TournamentCreateComponent },
Ok this is wrong, you can use child routes instead

2023-03-24 00:02 UTC, Fireinfern commented on src/app/views/tournaments/tournament-create/tournament-create.component.html
> +            <mat-radio-group ([ngModel])="selectedPlayer">
Dont use ngModel yet, thats for FormGroup and Validations

2023-03-25 01:04 UTC, merged