Feature/login register services
Fireinfern/tournament-frontend pull request #8
Opened 2023-03-29 23:37 UTC by Theepanguna

Based on the advice on Login service, I did the register service.

2023-03-29 23:59 UTC, Fireinfern requested changes
Confirm if you already tested it, with and it returns the appropieate responses for the requests.

2023-03-29 23:59 UTC, Fireinfern commented on src/app/services/login.service.ts
> +  // }
If not needed remove this comment

2023-03-30 00:01 UTC, Theepanguna commented on src/app/services/login.service.ts
> +  // }
sure

2023-03-30 12:24 UTC, Theepanguna commented
Adjusted the Login parsing username and password, but getting error when using matdialogref for register

2023-03-30 12:25 UTC, Theepanguna commented
@respatica hi, did some login and register form control, can you complete the balance or guide.

2023-03-31 23:23 UTC, Theepanguna commented
I have added error notification to the user when login failed. Added password and confirm password checking and prompting  dialog for user

2023-04-01 17:19 UTC, Theepanguna commented
HI , Could you please review this at your free time. cheers!

2023-04-03 19:54 UTC, Fireinfern approved these changes
LGTM

2023-04-03 19:54 UTC, merged